#!/usr/bin/env bash

brew update
grep -E "^-" formulae.txt | xargs -n 1 | grep -vE "^-" | xargs -L 1 brew reinstall

curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
rm -rf /usr/local/opt/nvim-macos
mv nvim-macos.tar.gz /usr/local/opt/
cd /usr/local/opt/ && tar xzf nvim-macos.tar.gz
