#!/usr/bin/env bash

rm -f ~/.zshrc
rm -f ~/.zlogin
ln -s ~/Code/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/Code/dotfiles/zsh/.zlogin ~/.zlogin

# trying out not using ohmyzsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
rm -f ~/.oh-my-zsh/custom/themes/johann2357.zsh-theme
# ln -s ~/Code/dotfiles/zsh/johann2357.zsh-theme ~/.oh-my-zsh/custom/themes/johann2357.zsh-theme
