#!/usr/bin/env bash

rm -rf ~/.config/nvim
ln -s $(pwd) ~/.config/nvim

# Install requirements
python3 -m pip install --user -U pipx
python3 -m pipx ensurepath
python3 -m pip install -r requirements.txt -U

# Required for LSP
pipx install 'python-language-server[all]' --force
