#!/usr/bin/env bash

# Adapted from: ThePrimeagen

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/syntax

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/Code/dotfiles/neovim/$f ~/.config/nvim/$f
done

# Install Plug
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install requirements
pip install -r requirements.txt

# TODO: Install pipx requirements (manually for now)
pipx install 'python-language-server[all]'
