#!/usr/bin/env bash

mkdir -p ~/.config/nvim/

to_link=("init.vim"  "lua"  "plugin"  "after", "ftdetect")

for elem in ${to_link[*]}; do
    echo "recreating $elem"
    rm -rf ~/.config/nvim/$elem
    ln -s ~/Code/dotfiles/neovim/$elem ~/.config/nvim/$elem
done

# Install Plug
if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
    echo "installing Plug"
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Install requirements
pip install -r requirements.txt -U

# Required for LSP
pipx install 'python-language-server[all]' --force
